# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Sophie Greenwood
tagline:          'Personal Website'
description:      'PhD Student @ Cornell'
url:              https://sophiejg.github.io/
baseurl:          /

# author:
#   name:           'Sophie Greenwood (edited from Hyde by Mark Otto)'
#   url:            https://twitter.com/s_j_greenwood

plugins:          [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
